### ISSUE TITLE
New Low Level Mastery Issue

### ISSUE THREAD

**Issue by dejoblue** [dejoblue/DejaCharacterStats#59] opened 2017-06-05 10:46 UTC
I merged many new pulls into 720Beta but now mastery is only hidden for Mastery Rating on my low level characters. Regular mastery is still yellow on low level characters.

**Comment by Kakjens** [comment] 2017-06-05 13:53
Not exactly clear what did you mean here but I believe there are inconsistences in displaying mastery and mastery rating names for low level characters. Found a possible reason why it happens. But first will probably need to check that everything what was intended for merging is merged.
Edit. Interesting that in not-merged version I see the correct code.

**Comment by Kakjens** [comment] 2017-06-05 17:50
Fixed in #61

**Closed as completed** 2017-06-15 19:37 UTC
